services:
  auth-service:
    networks:
      - microservice-network
  user-service:
    networks:
      - microservice-network
networks:
  microservice-network:
    name: "${COMMON_NETWORK:-microservice-network}"
    driver: bridge